update

diff --git a/.github/workflows/build_openwrt_x86_64.yml b/.github/workflows/build_openwrt_x86_64.yml
--- a/.github/workflows/build_openwrt_x86_64.yml
+++ b/.github/workflows/build_openwrt_x86_64.yml
@@ -28,28 +28,27 @@ jobs:
             zip_name_list=($(bash build_images.sh $distro false x86_64 | tail -n 1))
             release_id=$(curl -s -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/oneclickvirt/incus_images/releases/tags/$distro" | jq -r '.id')
             for file in "${zip_name_list[@]}"; do
-                echo "Checking if $file already exists in release..."
-                existing_asset_id=$(curl -s -H "Accept: application/vnd.github.v3+json" \
-                  "https://api.github.com/repos/oneclickvirt/incus_images/releases/$release_id/assets" \
-                  | jq -r --arg name "$(basename "$file")" '.[] | select(.name == $name) | .id')
-                if [ -n "$existing_asset_id" ]; then
-                    echo "Asset $file already exists in release, deleting existing asset..."
-                    delete_response=$(curl -s -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/oneclickvirt/incus_images/releases/assets/$existing_asset_id")
-                    echo "$delete_response"
-                    if [ $? -eq 0 ] && ! echo "$delete_response" | grep -q "error"; then
-                        echo "Existing asset deleted successfully."
-                    else
-                        echo "Failed to delete existing asset. Skipping file upload..."
-                        rm -rf $file
-                        continue
-                    fi
-                else
-                    echo "No $file file."
-                fi
                 echo "Building $distro and packge zips"
                 bash build_images.sh $distro true x86_64
-                # >/dev/null 2>&1
                 if [ -f "$file" ] && [ $(stat -c %s "$file") -gt 1048576 ]; then
+                    echo "Checking if $file already exists in release..."
+                    existing_asset_id=$(curl -s -H "Accept: application/vnd.github.v3+json" \
+                      "https://api.github.com/repos/oneclickvirt/incus_images/releases/$release_id/assets" \
+                      | jq -r --arg name "$(basename "$file")" '.[] | select(.name == $name) | .id')
+                    if [ -n "$existing_asset_id" ]; then
+                        echo "Asset $file already exists in release, deleting existing asset..."
+                        delete_response=$(curl -s -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/oneclickvirt/incus_images/releases/assets/$existing_asset_id")
+                        echo "$delete_response"
+                        if [ $? -eq 0 ] && ! echo "$delete_response" | grep -q "error"; then
+                            echo "Existing asset deleted successfully."
+                        else
+                            echo "Failed to delete existing asset. Skipping file upload..."
+                            rm -rf $file
+                            continue
+                        fi
+                    else
+                        echo "No $file file."
+                    fi
                     echo "Uploading $file to release..."
                     curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                       -H "Content-Type: application/zip" \
