Update build_apt_arm64.yml

diff --git a/.github/workflows/build_apt_arm64.yml b/.github/workflows/build_apt_arm64.yml
--- a/.github/workflows/build_apt_arm64.yml
+++ b/.github/workflows/build_apt_arm64.yml
@@ -8,7 +8,7 @@ jobs:
     runs-on: ubuntu-latest
     name: Build on ubuntu-18.04 armv7
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v2
       - uses: uraimo/run-on-arch-action@v2
         name: Run commands
         id: runcmd
@@ -24,60 +24,46 @@ jobs:
           run: |
             uname -a
             echo ::set-output name=uname::$(uname -a)
-
-      - name: Get the output
-        # Echo the `uname` output parameter from the `runcmd` step
-        run: |
-          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
-
-      - uses: actions/checkout@v2
-  
-      - name: check path
-        run: |
-          pwd
-      - name: Configure Git
-        run: |
-          git config --global user.name "daily-update"
-          git config --global user.email "tg@spiritlhl.top"
-        
-      - name: Build and Upload Images
-        run: |
-          distros=("kali")
-          # ("debian" "ubuntu" "kali" "centos" "almalinux" "rockylinux" "alpine" "openwrt" "oracle" "archlinux")
-          for distro in "${distros[@]}"; do
-              zip_name_list=($(bash build_images.sh $distro false | tail -n 1))
-              release_id=$(curl -s -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/oneclickvirt/incus_images/releases/tags/$distro" | jq -r '.id')
-              for file in "${zip_name_list[@]}"; do
-                  echo "Checking if $file already exists in release..."
-                  existing_asset_id=$(curl -s -H "Accept: application/vnd.github.v3+json" \
-                    "https://api.github.com/repos/oneclickvirt/incus_images/releases/$release_id/assets" \
-                    | jq -r --arg name "$(basename "$file")" '.[] | select(.name == $name) | .id')
-                  if [ -n "$existing_asset_id" ]; then
-                      echo "Asset $file already exists in release, deleting existing asset..."
-                      delete_response=$(curl -s -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/oneclickvirt/incus_images/releases/assets/$existing_asset_id")
-                      echo "$delete_response"
-                      if [ $? -eq 0 ] && ! echo "$delete_response" | grep -q "error"; then
-                          echo "Existing asset deleted successfully."
-                      else
-                          echo "Failed to delete existing asset. Skipping file upload..."
-                          rm -rf $file
-                          continue
-                      fi
-                  else
-                      echo "No $file file."
-                  fi
-                  echo "Building $distro and packge zips"
-                  bash build_images.sh $distro true
-                  # >/dev/null 2>&1
-                  if [ -f "$file" ] && [ $(stat -c %s "$file") -gt 10485760 ]; then
-                      echo "Uploading $file to release..."
-                      curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-                        -H "Content-Type: application/zip" \
-                        --data-binary @"$file" \
-                        "https://uploads.github.com/repos/oneclickvirt/incus_images/releases/$release_id/assets?name=$(basename "$file")"
-                      rm -rf $file
-                  else
-                      echo "No $file or less than 10 MB"
-                  fi
-              done
-          done
+            pwd
+            apt-get install git -y
+            git config --global user.name "daily-update"
+            git config --global user.email "tg@spiritlhl.top"
+            distros=("kali")
+            # ("debian" "ubuntu" "kali" "centos" "almalinux" "rockylinux" "alpine" "openwrt" "oracle" "archlinux")
+            for distro in "${distros[@]}"; do
+                zip_name_list=($(bash build_images.sh $distro false | tail -n 1))
+                release_id=$(curl -s -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/oneclickvirt/incus_images/releases/tags/$distro" | jq -r '.id')
+                for file in "${zip_name_list[@]}"; do
+                    echo "Checking if $file already exists in release..."
+                    existing_asset_id=$(curl -s -H "Accept: application/vnd.github.v3+json" \
+                      "https://api.github.com/repos/oneclickvirt/incus_images/releases/$release_id/assets" \
+                      | jq -r --arg name "$(basename "$file")" '.[] | select(.name == $name) | .id')
+                    if [ -n "$existing_asset_id" ]; then
+                        echo "Asset $file already exists in release, deleting existing asset..."
+                        delete_response=$(curl -s -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/oneclickvirt/incus_images/releases/assets/$existing_asset_id")
+                        echo "$delete_response"
+                        if [ $? -eq 0 ] && ! echo "$delete_response" | grep -q "error"; then
+                            echo "Existing asset deleted successfully."
+                        else
+                            echo "Failed to delete existing asset. Skipping file upload..."
+                            rm -rf $file
+                            continue
+                        fi
+                    else
+                        echo "No $file file."
+                    fi
+                    echo "Building $distro and packge zips"
+                    bash build_images.sh $distro true
+                    # >/dev/null 2>&1
+                    if [ -f "$file" ] && [ $(stat -c %s "$file") -gt 10485760 ]; then
+                        echo "Uploading $file to release..."
+                        curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+                          -H "Content-Type: application/zip" \
+                          --data-binary @"$file" \
+                          "https://uploads.github.com/repos/oneclickvirt/incus_images/releases/$release_id/assets?name=$(basename "$file")"
+                        rm -rf $file
+                    else
+                        echo "No $file or less than 10 MB"
+                    fi
+                done
+            done
